//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientSOAP.MathOperations {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MathOperations.IMathOperations")]
    public interface IMathOperations {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMathOperations/Add", ReplyAction="http://tempuri.org/IMathOperations/AddResponse")]
        int Add(int value1, int value2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMathOperations/Add", ReplyAction="http://tempuri.org/IMathOperations/AddResponse")]
        System.Threading.Tasks.Task<int> AddAsync(int value1, int value2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMathOperations/Substract", ReplyAction="http://tempuri.org/IMathOperations/SubstractResponse")]
        int Substract(int value1, int value2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMathOperations/Substract", ReplyAction="http://tempuri.org/IMathOperations/SubstractResponse")]
        System.Threading.Tasks.Task<int> SubstractAsync(int value1, int value2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMathOperations/Multiply", ReplyAction="http://tempuri.org/IMathOperations/MultiplyResponse")]
        int Multiply(int value1, int value2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMathOperations/Multiply", ReplyAction="http://tempuri.org/IMathOperations/MultiplyResponse")]
        System.Threading.Tasks.Task<int> MultiplyAsync(int value1, int value2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMathOperationsChannel : ClientSOAP.MathOperations.IMathOperations, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MathOperationsClient : System.ServiceModel.ClientBase<ClientSOAP.MathOperations.IMathOperations>, ClientSOAP.MathOperations.IMathOperations {
        
        public MathOperationsClient() {
        }
        
        public MathOperationsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MathOperationsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MathOperationsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MathOperationsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Add(int value1, int value2) {
            return base.Channel.Add(value1, value2);
        }
        
        public System.Threading.Tasks.Task<int> AddAsync(int value1, int value2) {
            return base.Channel.AddAsync(value1, value2);
        }
        
        public int Substract(int value1, int value2) {
            return base.Channel.Substract(value1, value2);
        }
        
        public System.Threading.Tasks.Task<int> SubstractAsync(int value1, int value2) {
            return base.Channel.SubstractAsync(value1, value2);
        }
        
        public int Multiply(int value1, int value2) {
            return base.Channel.Multiply(value1, value2);
        }
        
        public System.Threading.Tasks.Task<int> MultiplyAsync(int value1, int value2) {
            return base.Channel.MultiplyAsync(value1, value2);
        }
    }
}
